### ISSUE TITLE
Game Crash by Start with the LightAndShadow Mod Version 1.0.0

### ISSUE THREAD

**Issue by Mike74846** [KatatsumuriPan/LightAndShadow#3]
Hi,
 I have your new Mod test and the Game Crash by Start. It give no Crash Report but I have a Picture with the Answer of the Minecraft Launcher and I have the "debug.log" and the "latest.log" add. I hope this help you to found the Problem.

[2024-10-01-1.log.gz](https://github.com/user-attachments/files/17213379/2024-10-01-1.log.gz)
[debug-1.log.gz](https://github.com/user-attachments/files/17213380/debug-1.log.gz)

![Crash Report Light](https://github.com/user-attachments/assets/c86bd794-7a97-4329-ae69-2ce8b1468bbd)

**Comment by KatatsumuriPan** [comment]
I'll check it

**Comment by KatatsumuriPan** [comment]
Fixed in https://github.com/KatatsumuriPan/LightAndShadow/pull/4
Thank you for your report!
